---
- name: run akmods
  ansible.builtin.command:
    cmd: akmods

- name: restart vboxdrv
  ansible.builtin.service:
    name: xboxdrv
    state: restarted

- name: install extension pack
  ansible.builtin.debug:
    mgs: "Manually install VirtualBox Extension Pack: https://rpmfusion.org/Howto/VirtualBox#Install_VirtualBox_Extension_Pack"
