---
- name: kitty is installed
  ansible.builtin.package:
    name: kitty
    state: present

- name: symlink kitty dotfiles directory
  ansible.builtin.file:
    src: "{{ dotfiles_path }}/kitty"
    dest: /home/{{ user }}/.config/kitty
    state: link
    follow: false
    owner: "{{ user }}"
    group: "{{ user }}"

