---
karakeep_data_root: /srv/tier1/app_data/karakeep
karakeep_install_dir: /opt/karakeep
karakeep_secrets_file: /root/karakeep/.env

karakeep_port: 8910
karakeep_fqdn: "{{ ansible_facts['fqdn'] }}"
karakeep_url: "http://{{ ansible_facts['fqdn'] }}:{{ karakeep_port }}"

karakeep_version: release
meilisearch_version: v1.13.3
chrome_version: 124
