---
- name: create directory for {{ font }}
  ansible.builtin.file:
    path: /usr/local/share/fonts/{{ font }}
    state: directory
    owner: root
    group: root
    mode: 0775

- name: download and extract {{ font }}
  ansible.builtin.unarchive:
    remote_src: true
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/{{ nerd_fonts_version }}/{{ font }}.tar.xz
    dest: /usr/local/share/fonts/{{ font }}
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=rX
    creates: /usr/local/share/fonts/{{ font }}/README.md
